spring:
  datasource:
    url: jdbc:mysql://localhost:3307/dungcony?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  mail:
    host:
    port:
    username:
    password:
    from: OTP Service <dungcony@dungcony.io.vn>
  jpa:
    show-sql: true  # Dev environment - show SQL for debugging

  data:
    redis:
      port: 6379
      host: localhost
