spring:

  application:
    name: dungcony

  profiles:
    active: dev

  flyway:
    locations: classpath:db/migration
    baseline-on-migration: false
    repair-on-validate-error: true
    validate-on-migrate: true

  mail:
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: info
    com.dev.dungcony: debug
  file:
    name: logs/app.log

jwt:
  expiration: 300      # 5p
  refresh-expiration: 604800 # 7 ngày (s)

server:
  host: localhost